---
title: "Tutorial"
output: html_document
vignette: >
  %\vignetteIndexEntry{test.package tutorial}
  %\vignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(test.package)
library(ggplot2)
library(rbenchmark)
```

We use the following sample data set:
```{r}
y <- c(1,2,3,4,5,6,7,8,9,10)
x1 <- c(10,8,9,6,5,9,3,2,1,3)
x2 <- c(6,4,8,6,2,9,0,1,4,6)
prednames <- c("Speed", "Weight")
df <- data.frame(y,x1,x2)
```

To use linearreg with a single predictor:
```{r}
fit1 <- linearreg(y, x1, "Speed")
benchmark(linearreg(y, x1, "Speed"))
```  
Compare this with the lm() function:
```{r}
summary(lm(y~x1))
benchmark(lm(y~x1))
```

To get a plot of the data with a fit line:
```{r}
fitfun <- function(x) {
  fit1$Coefficients$Estimate[1] + fit1$Coefficients$Estimate[2]*x
}

ggplot(df, aes(x1, y)) +
  geom_point() +
  stat_function(fun = fitfun)
```

To use linearreg with multiple predictors:
```{r}
fit2 <- linearreg(y, cbind(x1,x2), c("Speed", "Weight"))
benchmark(linearreg(y, cbind(x1,x2), c("Speed", "Weight")))
```  
Compare this with the lm() function:
```{r}
summary(lm(y~x1+x2))
benchmark(lm(y~x1+x2))
```  
We can also fit without specifying predictor names:  
```{r}
fit2 <- linearreg(y, cbind(x1,x2))
```  
